### ISSUE TITLE
Nginx -v1.21 building deb file for debian buster.

### ISSUE THREAD

**Issue by huseyinozdemir** [google/nginx-sxg-module#100]
Hello,

I inspect this url https://github.com/google/nginx-sxg-module/blob/master/packaging/build_deb but  I can't find libnginx-mod.nginx.skeleton in related the path so I can't create deb file.

**Comment by twifkak** [comment]
Hi! So sorry for the delay.

Can you share logs of your command & your output? build_deb is successfully employed as part of a GitHub workflow: see https://github.com/google/nginx-sxg-module/actions/runs/764994177 for both the deb file outputs and the logs.

In particular, that file is created by the `apt-get source nginx-full` command earlier in build_deb.

**Comment by huseyinozdemir** [comment]
Hi,

Thank you for your answer.

I try to run nginx-sxg-modue after your response is 
```
dpkg -i libnginx-mod-http-sxg-filter_1.14.2-2+deb10u3_amd64.deb
Selecting previously unselected package libnginx-mod-http-sxg-filter.
(Reading database ... 115667 files and directories currently installed.)
Preparing to unpack libnginx-mod-http-sxg-filter_1.14.2-2+deb10u3_amd64.deb ...
Unpacking libnginx-mod-http-sxg-filter (1.14.2-2+deb10u3) ...
dpkg: dependency problems prevent configuration of libnginx-mod-http-sxg-filter:
 libnginx-mod-http-sxg-filter depends on nginx-common (= 1.14.2-2+deb10u3); however:
  Package nginx-common is not installed.

dpkg: error processing package libnginx-mod-http-sxg-filter (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libnginx-mod-http-sxg-filter
```

Our systems are
```
nginx version: nginx/1.21.0
debian_version: 10.10
```

**Comment by twifkak** [comment]
Thank you for the logs. It looks like the error is this one:
```
Package nginx-common is not installed.
```

You will need to `sudo apt install nginx` before you can run the `dpkg -i` command. Let me know how it goes.

**Comment by huseyinozdemir** [comment]
Hi,

I change version to Nginx v1.14.2 so that is successful.

Thanks.
