### ISSUE TITLE
Add startup message of this plugin

### ISSUE THREAD

**Issue by kumagi** [google/nginx-sxg-module#26]
When nginx is misconfigured, finding startup message is good clue to debug.
There should some informational log message in the initializing sequence.

**Comment by kumagi** [comment]
There should be ideal log message in our document too.

**Comment by kumagi** [comment]
On startup message, the plugin should output the settings and environment verbosely with NOTICE level.

**Comment by twifkak** [comment]
Is this fixed by #27? If not, can you clarify what other settings/environment should be output?

https://github.com/google/nginx-sxg-module/blob/c3c614e21484643e2549b0d7879f7529e7140251/ngx_http_sxg_filter_module.c#L713-L721

**Comment by kumagi** [comment]
Oh, thank you. This is already fixed as you said. I'll close this issue.
Please re-open or start new issue if anyone need yet another information in start up messages.
