### ISSUE TITLE
Add Vary header on outer response.

### ISSUE THREAD

**Issue by kumagi** [google/nginx-sxg-module#3]
When this plugin is enabled, the nginx will return SXG to the `qvalue` of the request header.
If there is any possibility of requested URL may returns SXG, `Vary` response header should always be appended.

**Comment by kumagi** [comment]
I think, using nginx feature like `add_header vary accept;` may be enough.

**Comment by sisidovski** [comment]
+1.

If the module is turned on, `accept` should always be added regardless of response type.
I'm not sure it's related or not, but the header can be one of there formats

One single header has multiple values
```
Vary: Accept, Accept-Encoding
```
Send two separate headers:
```
Vary: Accept
Vary: Accept-Encoding
```
https://tools.ietf.org/html/rfc7230#section-3.2.2

Also, be careful not to override existing Vary header from upstream. Just appending a new header sounds fair?  It looks `amppackager` simply add the header.
https://github.com/ampproject/amppackager
