### ISSUE TITLE
Subrequest doesn't happen if header value includes space

### ISSUE THREAD

**Issue by sisidovski** [google/nginx-sxg-module#40]
Testing subresource feature with a single line of Link header.

This doesn't work.
```
link: <https://example.com/static/style.css>; rel="preload"; as="style"
```

This works.
```
link: <https://example.com/static/style.css>;rel="preload";as="style"
```
The task extracting a url from the header might have some issues, but not sure.
So far I still don't test with multiple link headers, or comma separated values yet.

**Comment by orisano** [comment]
@sisidovski I check the latest version, this issue already fixed by https://github.com/google/nginx-sxg-module/commit/b19a5c69d8c29668c4fe19d2ac7336288465b964

**Comment by kumagi** [comment]
Also we may need another patch to ensure this case solved.

**Comment by twifkak** [comment]
Tested; this works now.
