### ISSUE TITLE
The plugin remains etag and last-modified header from upstream

### ISSUE THREAD

**Issue by sisidovski** [google/nginx-sxg-module#59]
The module should remove cache related headers in upstream response when it change the response by transforming to SXG. Otherwise static resources in a client cache wouldn't be updated even if SXG is out of date.

Static resources from upstream usually have cache related headers, such as `ETag` and `Last-Modified`. Those are useful to let a client know if the cache is still fresh or not. But so far the module doesn't change them when transforming the response to SXG. That causes expired SXG files (mainly static sub-resources) being stored for a long time unexpectedly.

At the moment, just removing cache related headers seems good way I think.

This is the diagram to illustrate what happens.
![Screen Shot 2020-06-17 at 12 29 33](https://user-images.githubusercontent.com/1642255/84851817-3e002000-b096-11ea-8a67-d7e28108fba9.png)

**Comment by twifkak** [comment]
Thanks for the detailed report with clear diagram! I think this would be a good initial fix, though the FR can be generalized further. The module should remove or replace all outer response headers that have been copied into the SXG as inner headers.

The outer response should include whatever headers are necessary for a typical static file response. I think the minimum is:

```
Date: <current time>
Content-Type: application/signed-exchange;v=b3
X-Content-Type-Options: nosniff
```

Other ones that are optional and dependent on the situation:
```
Vary: Accept                # publisher should set this in their nginx config
Transfer-Encoding: chunked  # dunno how this interacts with nginx modules
Connection: keep-alive      # ditto
```
