### ISSUE TITLE
Unexpected URLs in signed exchanges when using `try_files`

### ISSUE THREAD

**Issue by merlinnot** [google/nginx-sxg-module#74]
Hi! I'm leaving this issue here as there's a potential to improve the behavior of the module, however most importantly I wanted to leave somewhere a solution I found, so feel free to close if you don't see it relevant to fix. Other developers should be able to find it in closed issues as well.

A common way of implementing "clean URLs" (no trailing slashes) is to use `try_files` directive:

```
try_files $uri $uri/index.html =404;
```

The URL looks like this: `/foo/bar`, but the actual file lives in `/foo/bar/index.html`. When `try_files` is used alongside this module, the file path is in the signature instead of the requested URL: `/foo/bar/index.html`.

As a workaround, I'm now using `location` with a regular expression + `alias`:

```
location ~ ^/(.*) {
  rewrite ^/index(?:\.html|/)?$ / permanent;
  rewrite ^/(.*)/index(?:\.html|/)?$ /$1 permanent;
  rewrite ^/(.*)(?:\.html|/)$ /$1 permanent;

  alias /var/www/$1/index.html;
}
```

Result is the same when it comes to regular requests, however signatures contain a correct URL: `/foo/bar` with no `/index.html`.

**Comment by twifkak** [comment]
Thanks for the report! It seems like https://github.com/google/nginx-sxg-module/blob/663d652333308083c3e2a1358d2e66f9371d7ce0/ngx_http_sxg_filter_module.c#L678 should use [`unparsed_uri`](https://sourcegraph.com/github.com/nginx/nginx@2ba670a9257da1872b2dd7a866651b637a29997d/-/blob/src/http/ngx_http_request.h#L411) instead of `uri`.

Until then, your workaround is very interesting.

**Comment by merlinnot** [comment]
A small update: I actually had to use a different configuration because in Nginx there's no way to disable the Index Module, so my previous workaround doesn't work for the root (`/`) `index.html` file. Here's a fully working solution which uses a local proxy over a unix socket:

```
http {
  server {
    listen 8080;
    server_name my.domain;

    sxg on;
    sxg_certificate /var/certificates/sxg/sxg.crt;
    sxg_certificate_key /var/certificates/sxg/sxg.key;
    sxg_cert_url https://my.domain/certificate.cbor;
    sxg_validity_url https://my.domain/validity/resource.msg;

    location / {
      proxy_buffering off;
      proxy_http_version 1.1;
      proxy_pass http://unix:/var/run/nginx.sock;
      proxy_redirect off;
    }
  }

  server {
    listen unix:/var/run/nginx.sock;
    server_name my.local;
    root /var/www;

    location = /certificate.cbor {
      alias /var/certificates/sxg-public/sxg.cbor;
    }

    location ^~ /assets {
      # TODO: Change to 365d/31536000 once the conflict with SGX has a solution:
      # https://github.com/google/nginx-sxg-module/issues/76.
      expires 12h;
      add_header Cache-Control "immutable, max-age=43200, public";

      try_files $uri =404;
    }

    location / {
      rewrite ^/index(?:\.html|/)?$ / permanent;
      rewrite ^/(.*)/index(?:\.html|/)?$ /$1 permanent;
      rewrite ^/(.*)(?:\.html|/)$ /$1 permanent;

      # TODO: Change to a higher value once the conflict with SGX has
      # a solution: https://github.com/google/nginx-sxg-module/issues/76.
      expires 15m;
      add_header Cache-Control "max-age=1800, public, stale-while-revalidate=86400, stale-if-error=604800";

      try_files $uri/index.html =404;
    }
  }
}
```

**Comment by kumagi** [comment]
Thank you for report the bug, may I make a patch?
